<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>404 - Paybox</title>
    <link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<section class="hero is-fullheight is-danger">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                404
            </h1>
            <h2 class="subtitle">
                %%MESSAGE%%
            </h2>
            <p>
                Vous pouvez retourner à la <a href="/" title="page d'accueil">page d'accueil</a>.
            </p>
        </div>
    </div>
</section>
</body>
</html>
