<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Paybox</title>
    <link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
    <nav class="navbar has-shadow">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    Paybox Admin
                </a>
            </div>
            <div class="navbar-end navbar-menu">
                <a class="navbar-item" href="/produit">Produits</a>
                <a class="navbar-item" href="#">Clients (soon™)</a>
            </div>
        </div>
    </nav>
</header>
<section class="section">
    <div class="container">
        <?= $content ?>
    </div>
</section>
</body>
</html>

