<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Paybox</title>
	<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
	<link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
	<nav class="nav has-shadow">
		<div class="nav-left">
			<a class="nav-item is-brand" href="/">
				PayboxAdmin
			</a>
		</div>

		<span class="nav-toggle">
                <span></span>
                <span></span>
                <span></span>
            </span>
	</nav>
</header>
<section class="section">
	<div class="container">
		<div class="content">
			<h1>Que faire ?</h1>
			<h2>Paiements :</h2>
			<ul>
				<li><a href="/promo/all/EFFECTUE" title="Paiements effectués">Paiements effectués</a> / Version <a
						href="/promo/all/EFFECTUE/csv">CSV</a></li>
				<li><a href="/promo/all/A_CONFIRMER" title="Paiements à confirmer">Paiements à confirmer</a> / Version
					<a href="/promo/all/A_CONFIRMER/csv">CSV</a></li>
			</ul>
			<h2>Clients :</h2>
			<ul>
				<li>Liste des clients (soon™)</li>
				<li><a href="/promo" title="Liste des promos">Par promo</a></li>
			</ul>
			<h2>Produits :</h2>
			<ul>
				<li><a href="/produit" title="Liste des produits">Liste des produits</a></li>
			</ul>
		</div>
	</div>
</section>
</body>
</html>
