<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Paybox</title>
	<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
	<link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
	<nav class="nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a class="nav-item is-brand" href="/">
                    Paybox Admin
                </a>
            </div>
            <div class="nav-right nav-menu">
                <a class="nav-item" href="/produit">Produits</a>
                <a class="nav-item" href="#">Clients (soon™)</a>
            </div>
        </div>
	</nav>
</header>
<section class="section">
	<div class="container">
		<div class="content">
			<h1>Que faire ?</h1>
			<h2>Clients :</h2>
			<ul>
				<li>Liste des clients (soon™)</li>
			</ul>
			<h2>Produits :</h2>
			<ul>
				<li><a href="/produit" title="Liste des produits">Liste des produits</a></li>
			</ul>
		</div>
	</div>
</section>
</body>
</html>
