<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Paybox</title>
    <link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
    <nav class="nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a class="nav-item is-brand" href="/">
                    Paybox Admin
                </a>
            </div>
            <div class="nav-right nav-menu">
                <a class="nav-item" href="/produit">Produits</a>
                <a class="nav-item" href="#">Clients (soon™)</a>
            </div>
        </div>
    </nav>
</header>
<section class="section">
    <div class="container">

        <?php if (!empty($messages)): ?>
            <div class="notification is-<?=$messages[0][0]?>">
                <?=$messages[0][1]?>
            </div>
        <?php endif; ?>

        <form class="form" action="/produit/new" method="POST">
            <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label">Libellé</label>
            </div>
            <div class="field-body">
                <div class="field">
                <p class="control is-expanded">
                    <input class="input" type="text" placeholder="Libellé du produit"
                    required name="libelle">
                </p>
                </div>
            </div>
            </div>

            <div class="field is-horizontal">
            <div class="field-label is-normal">
                <label class="label">Montant du produit</label>
            </div>
            <div class="field-body">
                <div class="field">
                    <div class="field has-addons">
                        <div class="control">
                            <input class="input" type="number" placeholder="1000€" step="0.01" min=0
                            required name="montant">
                        </div>
                        <div class="control">
                            <a class="button is-static">€</a>
                        </div>
                    </div>
                    <p class="help is-info">
                        Il faut une <kbd>,</kbd> pour les décimales.
                    </p>
                </div>
            </div>
            </div>

            <div class="field is-horizontal">
            <div class="field-label"></div>
            <div class="field-body">
                <div class="field">
                <div class="control">
                    <label class="checkbox">
                    <input type="checkbox" name="open">
                    Disponible immédiatement ?
                    </label>
                </div>
                </div>
            </div>
            </div>

            <div class="field is-horizontal">
            <div class="field-label">
                <label class="label">Type de paiement</label>
            </div>
            <div class="field-body">
                <div class="field is-narrow">
                <div class="control">
                    <label class="radio">
                    <input type="radio" name="type_paiement" checked value="1">
                    1 fois
                    </label>
                    <label class="radio">
                    <input type="radio" name="type_paiement" value="2">
                    3 fois
                    </label>
                </div>
                </div>
            </div>
            </div>

            <div class="field is-horizontal">
            <div class="field-label">
                <!-- Left empty for spacing -->
            </div>
            <div class="field-body">
                <div class="field">
                <div class="control">
                    <button class="button is-primary">
                    Ajouter
                    </button>
                </div>
                </div>
            </div>
            </div>
        </form>
    </div>
</section>
</body>
</html>
