<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Paybox</title>
    <link href="/css/bulma.0.5.1.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
    <nav class="nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a class="nav-item is-brand" href="/">
                    Paybox Admin
                </a>
            </div>
            <div class="nav-right nav-menu">
                <a class="nav-item" href="/produit">Produits</a>
                <a class="nav-item" href="#">Clients (soon™)</a>
            </div>
        </div>
    </nav>
</header>

<section class="section">
    <div class="container">
    <h2 class="subtitle">Nombre de paiements : <?= count($users) ?></h2>

    <p>
        🔙 Retourner au <a href="<?= $router->pathFor('produit-id', ['id' => $produit]) ?>">produit</a>.
    </p>

    <?php if (empty($users)): ?>
        <article class="message is-warning">
            <div class="message-header">
                Attention
            </div>
            <div class="message-body">
                Aucun résultat retourné.
            </div>
        </article>
    <?php endif; ?>

    Trier par status :
    <div class="tabs is-toggle is-small">
        <ul>
            <?php
            if (!empty($statuses)):
                foreach ($statuses as $s): ?>
                    <li <?php if ($s['y_status'] === $status) echo "class='is-active'" ?>>
                        <a href="?status=<?= $s['y_status'] ?>">
                            <?= ucfirst($s['y_status']) ?>
                        </a>
                    </li>
                <?php endforeach;
            endif; ?>
        </ul>
    </div>
    <div class="content">
        <p><a class="button is-primary is-outlined"
              href="<?= $router->pathFor('export', ['id' => $produit]) ?>?status=<?= $status ?> ">
              💾 Export CSV
            </a>
        </p>

        <table class="table is-striped is-narrow is-bordered">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Email</th>
                <th>Montant</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $paiement): ?>
                <tr>
                    <td><?= $paiement['c_nom'] ?> <sup><a href="/user/<?= $paiement['c_pk'] ?>"
                                                          title="Voir sa fiche">&para;</a></sup></td>
                    <td><?= $paiement['c_prenom'] ?></td>
                    <td><a href="mailto:<?= $paiement['c_email'] ?>"
                           title="Envoyer un e-mail"><?= $paiement['c_email'] ?></a></td>
                    <td><?= $paiement['p_montant'] ?> €</td>
                    <td><?= $paiement['y_status'] ?></td>
                    <td><?= date('d/m/Y H:i:s', strtotime($paiement['y_date'])) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    </div>
</section>
</body>
</html>
