    <h2 class="subtitle">Nombre de paiements : <?= count($users) ?></h2>

    <p>
        🔙 Retourner au <a href="<?= $router->pathFor('produit-id', ['id' => $produit]) ?>">produit</a>.
    </p>

    <?php if (empty($users)): ?>
        <article class="message is-warning">
            <div class="message-header">
                Attention
            </div>
            <div class="message-body">
                Aucun résultat retourné.
            </div>
        </article>
    <?php endif; ?>

    Trier par status :
    <div class="tabs is-toggle is-small">
        <ul>
            <?php
            if (!empty($statuses)):
                foreach ($statuses as $s): ?>
                    <li <?php if ($s['y_status'] === $status) echo "class='is-active'" ?>>
                        <a href="?status=<?= $s['y_status'] ?>">
                            <?= ucfirst($s['y_status']) ?>
                        </a>
                    </li>
                <?php endforeach;
            endif; ?>
        </ul>
    </div>
    <div class="content">
        <p><a class="button is-primary is-outlined"
              href="<?= $router->pathFor('export', ['id' => $produit]) ?>?status=<?= $status ?> ">
              💾 Export CSV
            </a>
        </p>

        <table class="table is-striped is-narrow is-bordered">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Email</th>
                <th>Montant</th>
                <th>Référence</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $paiement): ?>
                <tr>
                    <td><?= $paiement['c_nom'] ?> <sup><a href="/user/<?= $paiement['c_pk'] ?>"
                                                          title="Voir sa fiche">&para;</a></sup></td>
                    <td><?= $paiement['c_prenom'] ?></td>
                    <td><a href="mailto:<?= $paiement['c_email'] ?>"
                           title="Envoyer un e-mail"><?= $paiement['c_email'] ?></a></td>
                    <td><?= $paiement['y_montant'] ?> €</td>
                    <td><a href="/ref/<?= $paiement['y_reference'] ?>"
                        title="Voir la fiche référence">
                        <?= $paiement['y_reference'] ?>
                        </a>
                    </td>
                    <td><?= date('d/m/Y H:i:s', strtotime($paiement['y_date'])) ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
