        <?php if (isset($produit)) : ?>

            <?php if (!empty($messages)): ?>
                <div class="notification is-<?=$messages[0][0]?>">
                    <?=$messages[0][1]?>
                </div>
            <?php endif; ?>

            <div class="heading">
                <h1 class="title"><?= $produit['p_libelle'] ?></h1>
            </div>
            <hr/>
            <form action="/produit/<?= $produit['p_pk'] ?>/edit" method="POST">
                <div class="field">
                    <label class="label">Montant en euro</label>
                    <div class="control">
                        <input type="number" class="input" placeholder="1000€"
                            value="<?= $produit['p_montant'] ?>" name="montant"
                            min="0" step="0.001">
                    </div>
                    <p class="help is-info">Il faut mettre une <kbd>,</kbd> pour les décimales</p>
                </div>
                <div class="field">
                    <div class="control">
                        <label class="checkbox">
                            <input type="checkbox" <?php echo ($produit['p_open']) ? 'checked' : '' ?>
                                class="checkbox" name="open">
                            Ouvert ?
                        </label>
                    </div>
                    <p class="help is-info">Coché = ouvert; Décoché = indisponible</p>
                </div>
                <div class="field">
                    <p>Paiement en plusieurs fois :</p>
                    <div class="control">
                        <label class="radio">
                            <input type="radio" name="type_paiement" value="1"
                                <?php if($produit['p_type_paiement'] === "1"): ?>
                                    checked
                                <?php endif ?>
                            >
                            1 fois
                        </label>
                        <label class="radio">
                            <input type="radio" name="type_paiement" value="2"
                                <?php if($produit['p_type_paiement'] === "2"): ?>
                                    checked
                                <?php endif ?>
                            >
                            3 fois
                        </label>
                    </div>
                </div>
                <div class="field">
                    <button>Éditer</button>
                </div>
            </form>
            <hr>
            <p>
                <span class="icon">
                    💵
                </span>
                <a href="/produit/<?= $produit['p_pk'] ?>/paiements"
                    class="is-link">Liste des personnes ayant payés
                </a>
            </p>
        <?php else: ?>
            <div class="heading">
                <h1 class="title">Produits disponibles</h1>
            </div>
            <div class="columns is-multiline">
            <?php foreach ($produits as $produit): ?>
                <div class="panel column is-one-third">
                    <p class="panel-heading"> <?= $produit['p_libelle'] ?> </p>
                    <a class="panel-block"
                        href="/produit/<?= $produit['p_pk'] ?>">
                        <span class="panel-icon">⚙</span>
                        Configuration
                    </a>
                    <a class="panel-block"
                        href="/produit/<?= $produit['p_pk'] ?>/paiements">
                        <span class="panel-icon">💵</span>
                        Paiements
                    </a>
                </div>
            <?php endforeach; ?>
            </div>
        <?php endif; ?>
