<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"/>
	<title>Paybox</title>
	<link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
	<link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
	<nav class="nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a class="nav-item is-brand" href="/">
                    Paybox Admin
                </a>
            </div>
            <div class="nav-right nav-menu">
                <a class="nav-item" href="/produit">Produits</a>
                <a class="nav-item" href="#">Clients (soon™)</a>
            </div>
        </div>
	</nav>
</header>

<section class="section">
	<div class="container">
		<?php if (isset($produit)) : ?>
			<div class="heading">
				<h1 class="title"><?= $produit['p_libelle'] ?></h1>
			</div>
			<hr/>
            <div class="content">
                <form>
                    <label class="label">Montant en euro</label>
                    <input type="number" class="input is-disabled" placeholder="1000€"
                           value="<?= $produit['p_montant'] ?>">
                    <label class="label">Disponible</label>
                    <input type="checkbox" <?php echo ($produit['p_open']) ? 'checked' : '' ?>
                           class="input is-disabled">
                </form>
                <hr>
                <p>
                    Liste des personnes ayant payés » <a href="/produit/<?= $produit['p_pk'] ?>/users"
                                                         class="button is-outlined is-small is-link is-info">Voir</a>
                </p>
            </div>
		<?php else: ?>
			<div class="heading">
				<h1 class="title">Produits disponibles</h1>
			</div>
			<div class="content">
				<ul>
					<?php foreach ($produits as $produit): ?>
                        <li>
                            <a href="/produit/<?= $produit['p_pk'] ?>"><?= $produit['p_libelle'] ?></a>
                            » <a href="/produit/<?= $produit['p_pk'] ?>/users"
                                 class="button is-outlined is-small is-link is-info">Voir</a>
                        </li>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php endif; ?>
	</div>
</section>

</body>
</html>
