<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Paybox</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
    <nav class="nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a class="nav-item is-brand" href="/">
                    Paybox Admin
                </a>
            </div>
            <div class="nav-right nav-menu">
                <a class="nav-item" href="/produit">Produits</a>
                <a class="nav-item" href="#">Clients (soon™)</a>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <section class="section">
    <h2 class="subtitle">Nombre de paiements : <?= count($users) ?></h2>

	<?php if (empty($users)): ?>
        <article class="message is-warning">
            <div class="message-header">
                Attention
            </div>
            <div class="message-body">
                Aucun résultat retourné.
            </div>
        </article>
	<?php endif; ?>

	<?php if (!isset($args['status'])): ?>
        <article class="message is-info">
            <div class="message-header">
                Information
            </div>
            <div class="message-body">
                Par défaut, seul les paiements effectués sont affichés.
            </div>
        </article>
	<?php endif; ?>

    Trier par status :
    <div class="tabs is-toggle is-small">
        <ul>
            <li <?= (!isset($status)) ? 'class=is-active' : '' ?>>
                <a href="#">All</a>
            </li>
			<?php
			if (!empty($statuses)):
				foreach ($statuses as $s): ?>
                    <li <?php if ($s['y_status'] === $status) echo "class='is-active'" ?>>
                        <a href="?status=<?= $s['y_status'] ?>">
	                        <?= ucfirst($s['y_status']) ?>
                        </a>
                    </li>
				<?php endforeach;
			endif; ?>
        </ul>
    </div>
        <p><a class="button is-primary is-outlined"
              href="<?= $router->pathFor('export', ['id' => $produit]) ?>?status=<?= $status ?> ">Export
                CSV</a></p>

        <table class="table is-striped is-narrow is-bordered">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Montant</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
			<?php foreach ($users as $paiement): ?>
                <tr>
                    <td><?= $paiement['c_nom'] ?> <sup><a href="/user/<?= $paiement['c_pk'] ?>"
                                                          title="Voir sa fiche">&para;</a></sup></td>
                    <td><?= $paiement['c_prenom'] ?></td>
                    <td><?= $paiement['p_montant'] ?> €</td>
                    <td><?= $paiement['y_status'] ?></td>
                    <td><?= date('d/m/Y H:m:i', strtotime($paiement['y_date'])) ?></td>
                </tr>
			<?php endforeach; ?>
            </tbody>
        </table>
    </section>
</div>
</body>
</html>
