<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Paybox</title>
    <link href="/css/bulma.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<header>
    <nav class="nav has-shadow">
        <div class="container">
            <div class="nav-left">
                <a class="nav-item is-brand" href="/">
                    Paybox Admin
                </a>
            </div>
            <div class="nav-right nav-menu">
                <a class="nav-item" href="/produit">Produits</a>
                <a class="nav-item" href="#">Clients (soon™)</a>
            </div>
        </div>
    </nav>
</header>
<section class="section">
    <div class="container">
        <h1 class="title"><?=$reference?></h1>
        <h2 class="subtitle">
            › <a href="/produit/<?=$referenceInfo['produit']['p_pk']?>" title="Produit">
                <?=$referenceInfo['produit']['p_libelle']?>
            </a>
        </h2>

        <div class="columns">
            <div class="column is-one-quarter">
                <div class="panel">
                    <p class="panel-heading">
                        Informations client
                    </p>
                    <a class="panel-block has-text-centered" href="/user/<?=$referenceInfo['user']['c_pk']?>" title="Utilisateur">
                        <?php printf('%s %s',
                            $referenceInfo['user']['c_prenom'],
                            $referenceInfo['user']['c_nom'])
                        ?>
                    </a>
                    <div class="panel-block">
                        <a class="button is-primary is-outlined is-fullwidth"
                           href="mailto:<?=$referenceInfo['user']['c_email']?>"
                           title="Mail">
                        Envoyer un email
                        </a>
                    </div>
                </div>
            </div>
            <div class="column">
                <div class="content">
                    <h3>Historique :</h3>
                    <table class="table is-narrow">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Somme</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        if (empty($referenceInfo['paiements'])):
                            echo '<tr><td colspan="3">Aucun historique</td></tr>';
                        else:
                            foreach ($referenceInfo['paiements'] as $paiement):
                                ?>
                                <tr>
                                    <td><?= date('\L\e d/m/Y à H:i:s', strtotime($paiement['y_date'])) ?></td>
                                    <td><?= $paiement['y_status'] ?></td>
                                    <td><?= $paiement['p_montant'] ?> €</td>
                                </tr>
                                <?php
                            endforeach;
                        endif;
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>
